<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>async 함수</title>
</head>
<body>
    <h1>async 함수와 프라미스와 동기화!</h1>
    <h2>async 함수는 자동 프라미스화 기능이 존재한다...(잘 사용하진않음)</h2>
    <pre>
      async function name(){
        return data;

        ==return new Promise((resolve)=>{
        resolve(data)

      )
    </pre>
    <h2>★★★async 함수는 await 연산자로 Promise 객체의 then함수를 실행할 수 있다.
        그리고, then의 첫번째 콜백 함수의 매개변수를 반환한다..
    </h2>
    <pre>
        new Promise((resolve)=>{
            .....처리
            resolve(결과);
        }).then((결과)=>{
            ....결과를 처리
        })...

        async function name(){
            let 결과 = await new Promse((resolve)=>{
                ...resolve
                resolve(결과);
            })
        ...처리...
    </pre>
    <p>콜백지옥을 벗어나기 위해 Promise가 도입되었지만 프라미스지옥을 안겨주었다... async함수가 해결</p>
    <h2>async에서 에러처리(쉽다)</h2>

    <pre>
        new Promise((resolve, reject)=>{
            ...오류 or 예상치 않은 상황
            reject(new Error("오류내용");

        }).then(()=>{},("오류내용")=>{
            ...오류를 처리
        })

        or

             new Promise((resolve, reject)=>{
            ...오류 or 예상치 않은 상황
            reject(new Error("오류내용");

        }).then((resolve)=>{
        }).catch("오류내용")=>{
            ...오류를 처리
        });

        // async에서는 Promise처럼 reject나 catch는 사용하지 않고 일반적인 예외처리를 함.
        async 함수(){
            try{

            let 처리 = await new Promise((resolve)=>{ resolve(처리)}
            } catch (e){
            ...오류를 처리
            }
        }
        // 통신 실패인 404 500 오류는 trycatch로 잡을 수 있는 오류가 아님...
        // trycatch는 문법오류같은걸 말함+

    </pre>
    <h2>스레드를 사용하는 이유와 스레드 동기화와 Promise.All</h2>
    <ul>
        <li>멀티스레드를 사용하는 이유 1: 여러 일을 동시에 처리</li>
        <li>멀티스레드를 사용하는 이유 2: 시간,비용 절약</li>
        <li>멀티스레드(app이 일하는 단위)를 사용하는 이유 3:
            프로세스(cpu 일하는 단위)를 더 효율적으로 사용
        </li>
        <li>
            Promise와 async를 쓸 때 자주하는 실수로 효율적으로 실행하기 위해 생성하는 멀티스레드를 모두 동기화하는 일을 하곤한다..
        </li>
        <li>Promise.all()을 이용해서 비동기 실행을 동시에 동기화 할 수 있다.</li>
    </ul>
<script>
    async function a(){
    return "1";
    } //현재 아래 함수의 resolve("1")의 상태와 같기때문에 1을 실제로 얻으려면 then을 써서 받아와야함
    // a().then(()=>{})

    console.log(a())
    function a2(){
      return new Promise((resolve)=>{resolve("1")})
    }

    console.log(a2())

    function loadImgList(){
      fetch("ajax/imgList.html").then((resp)=>{
        return resp.text()
      }).then((html)=>{
        alert(html)
      })
    }
    async function loadImgListAsync(){
     const resp = await fetch("ajax/imgList.html"); //이렇게 써두면 then이 실행되고 첫 번째 함수에 해당하는 매개변수를 반환
     const html = await resp.text();
     alert(html);
    }

</script>
    <h2>imgList와 PersonList를 불러오세요!!
        <button id="loadImgAndPersonBtn">로드..!!</button>
    </h2>
    <p>
        <button id="loadImgAndPersonBtn2">PromiseAll로 로드..!!</button>
    </p>
    <div id="imgListCont"></div>
    <pre id="personListCont"></pre>
<script>
    loadImgAndPersonBtn.onclick=async()=>{

        console.time("11")
        const resp = await fetch("./ajax/imgList.html")
        //await 때문에 imgList가 통신이 완료될 때 까지 기다렸다가 personList와 통신해버림
        const resp2 = await fetch("./ajax/personList.json")

        let html = await resp.text();
        let json = await resp2.text();
        imgListCont.innerHTML=html;
        personListCont.innerText=json;
        //커더란 실수를 저질렀다...!!

        console.timeEnd("11")
    }

    loadImgAndPersonBtn2.onclick=async()=>{
        console.time("22")
        const[resp, resp2]= await Promise.all([fetch("./ajax/imgList.html") ,fetch("./ajax/personList.json")]);

        let html = await resp.text();
        let json = await resp2.text();
        imgListCont.innerHTML=html;
        personListCont.innerText=json;

        console.timeEnd("22")
    }
</script>
</body>
</html>